### ISSUE TITLE
Ответы на оставшиеся задания курса

### ISSUE THREAD

**Issue by Lightning123-ib** [manchenkoff/geekbrains-python-exercises#1]
Артем, добрый вечер!

Я учусь на курсе "Основы Python. Интерактивный курс" в GeekBrains.
В этом репозитории (geekbrains-python-exercises) приведены ответы только на первые 5 модулей из 8.
Могли бы добавить коды по задачам из модулей 6-8, чтобы можно было перепроверить себя после отправки своих ответов? Увы, GeekBrains пока не записал видео с разборами заданий и вряд ли это сделает в ближайшее время...

Заранее большое спасибо!

**Comment by manchenkoff** [comment]
Добрый день, здесь находятся ответы не на домашние работы по каждому уроку, а именно по "тренажеру" через Stepik.

Как раз в данный момент я занимаюсь записью всех решений по каждому уроку курса, до 1 августа передам все записи в продакшн.
